"""
Example: 08_sampling.py

01_server.py's summarize_via_client tool asks the CLIENT to run an
LLM completion instead of calling a model itself - verified round
trip using a real local Ollama model in the client's
sampling_callback. Ties back to
docs/15-Sampling-Servers-Requesting-Completions.md.

Run:
    ollama pull llama3.1:8b
    pip install mcp openai
    python 08_sampling.py
"""

import asyncio

import mcp.types as types
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from openai import OpenAI

SERVER = StdioServerParameters(command="python3", args=["01_server.py"])
llm_client = OpenAI(base_url="http://localhost:11434/v1", api_key="ollama")


async def handle_sampling(context, params) -> types.CreateMessageResult:
    # The CLIENT decides how (and whether) to fulfill the server's
    # request - here we route it to a real local Ollama model.
    messages = [{"role": m.role, "content": m.content.text} for m in params.messages]
    response = llm_client.chat.completions.create(
        model="llama3.1:8b", messages=messages, max_tokens=params.maxTokens or 100
    )
    return types.CreateMessageResult(
        role="assistant",
        content=types.TextContent(type="text", text=response.choices[0].message.content),
        model="llama3.1:8b",
    )


async def main():
    async with stdio_client(SERVER) as (read, write):
        async with ClientSession(read, write, sampling_callback=handle_sampling) as session:
            await session.initialize()
            result = await session.call_tool(
                "summarize_via_client",
                {"text": "The service ran out of memory after a slow leak over several hours and crashed."},
            )
            print("Tool result (generated by the CLIENT's model, requested by the SERVER):")
            print(" ", result.content[0].text)


if __name__ == "__main__":
    asyncio.run(main())
